version: '3.8'

services:
  web:
    build:
      context: ./PassVault
      dockerfile: Dockerfile.prod
    command: gunicorn PassVault.wsgi:application -c gunicorn_config.py
    volumes:
      - ./PassVault/:/usr/src/app/
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      ./.env.db.prod
  ngnix:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: