version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./PassVault:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./PassVault/.env
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=somewhat
      - POSTGRES_DB=passvault_db

volumes:
  postgres_data: