version: '3.8'

services:
  web:
    build:
      context: ./PassVault
      dockerfile: Dockerfile.prod
    command: gunicorn PassVault.wsgi:application -c gunicorn_config.py
    volumes:
      - ./PassVault/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
    entrypoint: /usr/src/app/entrypoint.prod.sh
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      ./.env.db.prod

volumes:
  postgres_data: